import { EXTRA_PITFALLS } from './data-extra.js';

/** 避坑案例库 */
export const CATEGORIES = ['网恋', '暧昧', '异地', '见家长', '彩礼', '出轨', '相亲', '冷暴力'];

const PITFALLS_BASE = [
  {
    id: 1,
    category: '网恋',
    title: '红包陷阱：转账备注写借款',
    lesson: '网恋三个月未见面，对方以急事为由要求转账5000元，备注写「借款」。分手后对方凭转账记录起诉追债，法院认定借贷关系成立。',
    steps: '1. 未见面绝不转账\n2. 任何借钱请求直接拒绝\n3. 已转账保留聊天记录证明非自愿',
    cost: '金钱',
    helped: 2847,
    hasAudio: true,
    hasVideo: true,
    quiz: { q: '网恋未见面时，对方要钱最正确的做法是？', options: ['先借一点试试', '一律拒绝转账', '备注赠予再转'], a: 1 },
  },
  {
    id: 2,
    category: '暧昧',
    title: '备胎陷阱：只聊天不确认关系',
    lesson: '暧昧半年，对方总说「再等等」「还没准备好」，却同时和其他人约会。浪费大量情绪价值与时间。',
    steps: '1. 设定3个月期限\n2. 到期直接问「我们要不要正式在一起」\n3. 回避或拖延=离开',
    cost: '时间',
    helped: 1923,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '暧昧超过3个月仍不确认关系，建议？', options: ['继续等', '设期限并直接确认', '暗中调查'], a: 1 },
  },
  {
    id: 3,
    category: '异地',
    title: '冷暴力：已读不回超过72小时',
    lesson: '异地恋爱中对方突然消失，消息已读不回。当事人反复道歉、追问，换来的是更长的沉默。',
    steps: '1. 发一条底线信息：「我需要沟通，X日前谈」\n2. 到期无回应则止损\n3. 停止自我贬低式道歉',
    cost: '情感',
    helped: 3156,
    hasAudio: true,
    hasVideo: true,
    quiz: { q: '异地冷暴力已读不回，首先应？', options: ['连续道歉', '发底线沟通信息', '找共同朋友施压'], a: 1 },
  },
  {
    id: 4,
    category: '见家长',
    title: '面子陷阱：为讨好对方家庭过度消费',
    lesson: '第一次见面家长，买贵重礼品、包餐厅，对方家庭视为理所当然，婚后要求持续高规格付出。',
    steps: '1. 礼物适度有心意即可\n2. 观察对方家庭是否双向尊重\n3. 单方面索取=红线',
    cost: '金钱',
    helped: 876,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '第一次见家长，礼物应？', options: ['越贵越好', '适度有心意', '空手去'], a: 1 },
  },
  {
    id: 5,
    category: '彩礼',
    title: '彩礼陷阱：先付后反悔',
    lesson: '订婚时支付高额彩礼，对方悔婚后拒绝返还，家庭陷入长期纠纷。',
    steps: '1. 了解当地习俗与法律规定\n2. 大额支付需书面约定\n3. 保留全部支付凭证',
    cost: '金钱',
    helped: 1542,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '彩礼大额支付前必须？', options: ['口头承诺即可', '书面约定并留凭证', '只信对方父母'], a: 1 },
  },
  {
    id: 6,
    category: '出轨',
    title: '原谅陷阱：无底线二次信任',
    lesson: '发现出轨后对方痛哭道歉，承诺改正。三个月内再次出轨，且更加隐蔽。',
    steps: '1. 第一次出轨需有具体改正行动\n2. 无行动只有道歉=无效\n3. 二次出轨建议果断离开',
    cost: '情感',
    helped: 2234,
    hasAudio: true,
    hasVideo: true,
    quiz: { q: '出轨后仅有道歉无行动，应？', options: ['再给一次机会', '视为无效继续观察', '立刻结婚稳住'], a: 1 },
  },
  {
    id: 7,
    category: '相亲',
    title: '条件陷阱：只谈物质不谈相处',
    lesson: '相亲对象开门见山问房车户口，相处三次即谈结婚条件，忽略性格与价值观匹配。',
    steps: '1. 至少约会5次再谈条件\n2. 观察日常相处细节\n3. 纯条件交换需警惕',
    cost: '时间',
    helped: 1105,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '相亲第三次就谈房车，应？', options: ['立刻答应', '至少5次约会再谈', '反向提更高要求'], a: 1 },
  },
  {
    id: 8,
    category: '暧昧',
    title: '朋友圈陷阱：仅对你可见的暧昧',
    lesson: '对方朋友圈对你展示单身、伤感内容，对他人却是恋爱中状态。典型养鱼手段。',
    steps: '1. 要求公开关系或介绍朋友\n2. 拒绝=你在备胎池\n3. 不猜，直接问',
    cost: '情感',
    helped: 1689,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '朋友圈对你单身对他人恋爱中，说明？', options: ['害羞', '可能在养鱼', '系统bug'], a: 1 },
  },
  {
    id: 9,
    category: '网恋',
    title: '照骗陷阱：见面即幻灭',
    lesson: '网聊半年，照片精致。见面发现严重不符，对方却指责你「只看外表」。',
    steps: '1. 一个月内需视频验证\n2. 三个月内安排见面\n3. 拒绝见面=高风险',
    cost: '时间',
    helped: 2456,
    hasAudio: true,
    hasVideo: true,
    quiz: { q: '网恋多久应视频验证？', options: ['不必', '一个月内', '结婚前夕'], a: 1 },
  },
  {
    id: 10,
    category: '冷暴力',
    title: '沉默陷阱：用消失惩罚你',
    lesson: '每次吵架对方就拉黑消失一周，你妥协后对方才出现。形成「惩罚式沉默」控制模式。',
    steps: '1. 不因恐惧妥协\n2. 明确「消失不是沟通方式」\n3. 重复发生则重新评估关系',
    cost: '情感',
    helped: 1876,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '吵架后对方习惯性消失一周，属于？', options: ['正常冷静', '惩罚式控制', '工作忙'], a: 1 },
  },
  {
    id: 11,
    category: '冷暴力',
    title: '情绪忽视：你的感受永远排最后',
    lesson: '你表达难过，对方回复「你想多了」。长期情感需求得不到回应，自我怀疑加重。',
    steps: '1. 用具体事件描述感受\n2. 观察对方是否愿意回应\n3. 持续忽视=情感不匹配',
    cost: '情感',
    helped: 1432,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '反复被说「你想多了」，应？', options: ['停止表达', '用具体事件再沟通', '自责'], a: 1 },
  },
  {
    id: 12,
    category: '网恋',
    title: '投资陷阱：带你「稳赚」理财',
    lesson: '网恋对象推荐平台投资，先小利后大额，平台无法提现。典型杀猪盘。',
    steps: '1. 绝不向网恋对象转账投资\n2. 核实平台资质\n3. 无法提现立即报警',
    cost: '金钱',
    helped: 3210,
    hasAudio: true,
    hasVideo: true,
    quiz: { q: '网恋对象推荐高回报理财，应？', options: ['小额试试', '拒绝并警惕杀猪盘', '拉朋友一起'], a: 1 },
  },
  {
    id: 13,
    category: '异地',
    title: '承诺陷阱：只说见面从不订票',
    lesson: '异地一年，对方每月承诺「下月见面」却从不订票。你投入越来越多，对方拖延。',
    steps: '1. 要求具体日期与车票截图\n2. 连续两次爽约则止损\n3. 不见面不升级承诺',
    cost: '时间',
    helped: 998,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '异地一年从未订票见面，建议？', options: ['继续等', '要求具体日期否则止损', '先去对方城市'], a: 1 },
  },
  {
    id: 14,
    category: '彩礼',
    title: '攀比陷阱：彩礼年年加价',
    lesson: '订婚前后彩礼被要求多次追加，理由为「别人家更高」。家庭矛盾激化。',
    steps: '1. 婚前书面确认金额\n2. 追加需双方家庭书面同意\n3. 超出承受能力果断止损',
    cost: '金钱',
    helped: 765,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '订婚后彩礼被要求追加，应？', options: ['尽量满足', '书面确认或止损', '只告诉伴侣'], a: 1 },
  },
  {
    id: 15,
    category: '出轨',
    title: '暧昧边界：与异性「兄弟/闺蜜」无界限',
    lesson: '伴侣与异性频繁深夜聊天、单独旅行，称「只是朋友」。信任反复被击穿。',
    steps: '1. 明确边界底线\n2. 看行动是否调整\n3. 反复越界=重新选择',
    cost: '情感',
    helped: 1567,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '伴侣与异性深夜单独聊天，应？', options: ['不管', '明确边界并看行动', '同样去做报复'], a: 1 },
  },
  {
    id: 16,
    category: '相亲',
    title: '急婚陷阱：认识两周催领证',
    lesson: '相亲对象急于确定关系、催婚，回避深入了解。婚后发现性格严重不合。',
    steps: '1. 至少相处3个月\n2. 见朋友与家人\n3. 急催=警惕动机',
    cost: '时间',
    helped: 654,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '认识两周就催领证，应？', options: ['效率高的表现', '放慢并深入了解', '立刻答应'], a: 1 },
  },
  {
    id: 17,
    category: '见家长',
    title: '站队陷阱：父母与你对立时TA不表态',
    lesson: '家长刁难你时，伴侣沉默或站父母一方。婚后类似矛盾反复上演。',
    steps: '1. 婚前观察TA立场\n2. 要求对事不对人\n3. 长期站队父母=红线',
    cost: '情感',
    helped: 543,
    hasAudio: false,
    hasVideo: false,
    quiz: { q: '见家长被刁难伴侣沉默，说明？', options: ['正常', '需观察其长期立场', '你应该讨好'], a: 1 },
  },
  {
    id: 18,
    category: '暧昧',
    title: '礼物陷阱：只收礼不确认关系',
    lesson: '对方接受昂贵礼物与付出，却拒绝确认恋爱关系。物质与情感不对等。',
    steps: '1. 礼物适度\n2. 送礼后确认关系进展\n3. 只收不给名分=止损',
    cost: '金钱',
    helped: 1123,
    hasAudio: true,
    hasVideo: false,
    quiz: { q: '只收贵重礼物不确认关系，应？', options: ['送更多打动', '止损或明确要求', '继续等待'], a: 1 },
  },
];

export const PITFALLS = [...PITFALLS_BASE, ...EXTRA_PITFALLS];

export const HOT_TOPICS = [
  { text: '暧昧半年不确认关系怎么办？', count: 1284 },
  { text: '网恋没见面就借钱该借吗？', count: 967 },
  { text: '对方冷暴力已读不回', count: 856 },
  { text: '发现出轨要不要原谅？', count: 743 },
  { text: '彩礼谈崩如何直线沟通？', count: 621 },
];

export const SUCCESS_STORIES = [
  {
    tag: '避坑·暧昧',
    text: '看了「备胎陷阱」后设了3个月期限，对方拖延，我果断离开。两个月后遇到现在的伴侣，直线沟通，很幸福。',
    prompt: '暧昧半年不确认关系怎么办？',
    pitfallId: 2,
  },
  {
    tag: '避坑·网恋',
    text: '差点给网恋对象转账，问了Q问，按直线方案拒绝。后来才知道是惯犯。',
    prompt: '网恋没见面就借钱该借吗？',
    pitfallId: 1,
  },
  {
    tag: 'Q智慧',
    text: '用「再问一步」拿到了第一条消息的具体措辞，对方当晚就回复了，现在我们在一起。',
    prompt: '暧昧对象已读不回，第一条消息该怎么发？',
  },
  {
    tag: '避坑·冷暴力',
    text: '学会发底线信息后，看清对方不愿沟通，及时止损，不再内耗。',
    prompt: '对方冷暴力已读不回怎么办？',
    pitfallId: 3,
  },
];

export const COST_LABELS = { 金钱: 'money', 时间: 'time', 情感: 'emotion' };

/** 缘认知匹配：根据浏览/提问偏好 */
export const FATE_TYPES = [
  {
    id: 'straight',
    name: '直线沟通型',
    desc: '重视明确表态与可执行步骤，讨厌暧昧拖延。',
    pits: ['备胎陷阱', '急婚陷阱', '沉默陷阱'],
  },
  {
    id: 'safe',
    name: '安全边界型',
    desc: '看重信任与边界，对金钱与隐私敏感。',
    pits: ['红包陷阱', '投资陷阱', '暧昧边界'],
  },
  {
    id: 'slow',
    name: '慢热稳定型',
    desc: '需要较长观察期，重视家庭与长期承诺。',
    pits: ['面子陷阱', '彩礼陷阱', '站队陷阱'],
  },
];

export const UNLOCK_ITEMS = [
  { need: 50, title: '深度避坑专题', desc: '解锁 3 个高阶场景专题' },
  { need: 100, title: '情感教练答疑券', desc: '预约 1 次直线教练（演示）' },
  { need: 200, title: '定制避坑报告', desc: '基于提问记录生成个人报告（演示）' },
];

/** 高阶专题（50 分解锁） */
export const TOPICS = [
  {
    id: 'netlove',
    name: '网恋防骗专题',
    desc: '借钱、投资、照骗、代购、签证等 6 大坑一次学完',
    pitIds: [1, 9, 12, 20, 28, 36, 44],
  },
  {
    id: 'ambiguous',
    name: '暧昧止损专题',
    desc: '备胎、朋友圈、礼物、深夜、节日等直线退出',
    pitIds: [2, 8, 18, 21, 29, 37, 45],
  },
  {
    id: 'marriage',
    name: '婚恋家庭专题',
    desc: '彩礼、见家长、婚前协议、急婚与隐瞒',
    pitIds: [4, 5, 7, 16, 17, 24, 26, 32, 40, 42, 47, 48, 50],
  },
];
