# Create Cloudflare KV QTVQ_KV and update wrangler.toml
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup-kv.ps1

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
$WranglerToml = Join-Path $Root "wrangler.toml"

function Invoke-WranglerKvCreate([string]$Title, [switch]$Preview) {
    $args = @("wrangler", "kv", "namespace", "create", $Title)
    if ($Preview) { $args += "--preview" }
    Write-Host "> npx $($args -join ' ')"
    $out = & npx @args 2>&1 | Out-String
    Write-Host $out
    if ($out -match 'id\s*=\s*"([a-f0-9]{32})"') { return $Matches[1] }
    if ($out -match '"id"\s*:\s*"([a-f0-9]{32})"') { return $Matches[1] }
    throw "Cannot parse KV namespace id from wrangler output."
}

function Update-WranglerToml([string]$ProdId, [string]$PreviewId) {
    $content = Get-Content $WranglerToml -Raw -Encoding UTF8
    $block = @"
# QTVQ_KV - generated by scripts/setup-kv.ps1
[[kv_namespaces]]
binding = "QTVQ_KV"
id = "$ProdId"
preview_id = "$PreviewId"
"@
    if ($content -match '(?s)# QTVQ_KV[\s\S]*?preview_id\s*=\s*"[^"]+"') {
        $content = $content -replace '(?s)# QTVQ_KV[\s\S]*?preview_id\s*=\s*"[^"]+"', $block.TrimEnd()
    } elseif ($content -match '(?s)# 提问额度 / 会员 KV[\s\S]*?preview_id\s*=\s*"[^"]+"') {
        $content = $content -replace '(?s)# 提问额度 / 会员 KV[\s\S]*?preview_id\s*=\s*"[^"]+"', $block.TrimEnd()
    } else {
        $content = $content.TrimEnd() + "`r`n`r`n" + $block + "`r`n"
    }
    [System.IO.File]::WriteAllText($WranglerToml, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Updated wrangler.toml: id=$ProdId preview_id=$PreviewId"
}

Set-Location $Root

$whoami = & npx wrangler whoami 2>&1 | Out-String
if ($whoami -match 'not authenticated' -and -not $env:CLOUDFLARE_API_TOKEN) {
    Write-Host "ERROR: Run 'npx wrangler login' first, or set CLOUDFLARE_API_TOKEN." -ForegroundColor Red
    exit 1
}

Write-Host "=== QTVQ KV Setup ===" -ForegroundColor Cyan

Write-Host "[1/2] Production namespace QTVQ_KV"
$prodId = Invoke-WranglerKvCreate -Title "QTVQ_KV"

Write-Host "[2/2] Preview namespace QTVQ_KV"
$previewId = Invoke-WranglerKvCreate -Title "QTVQ_KV" -Preview

Update-WranglerToml -ProdId $prodId -PreviewId $previewId

Write-Host ""
Write-Host "Next: Cloudflare Dashboard -> Pages -> qtvq -> Functions -> KV bindings" -ForegroundColor Yellow
Write-Host "  Variable name: QTVQ_KV"
Write-Host "Done." -ForegroundColor Green
